# Generated by Django 5.2.17 on 2026-10-03 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='admin_response',
            field=models.TextField(blank=True),
        ),
    ]
